name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pac-Man Contribution SVG
        uses: maurodesouza/contribution-graph-action@v2
        with:
          user_name: aniketyadav1208
          theme: batman
